/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java-library")
    id("net.minecrell.plugin-yml.bukkit") version "0.5.2"
    id("xyz.jpenilla.run-paper") version "2.0.1"
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

repositories {
    mavenLocal()
    mavenCentral()
    gradlePluginPortal()

    maven("https://jitpack.io")
    maven("https://repo.panda-lang.org/releases")
    maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
}

dependencies {
    implementation("com.github.kangarko:Foundation:6.2.5") {
        exclude(group = "org.mineacademy.plugin", module = "*")
    }
    compileOnly("org.spigotmc.spigot-api:1.19.3-R0.1-SNAPSHOT")
    implementation("org.panda-lang:expressible:1.2.2")
    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
}

apply(plugin = "com.github.johnrengelman.shadow")
apply(plugin = "net.minecrell.plugin-yml.bukkit")
apply(plugin = "xyz.jpenilla.run-paper")
group = "xyz.jakubk15"
version = "1.0.0"
description = "ParcelLockers"
ant.importBuild("build.xml")

bukkit {
    main = "xyz.jakubk15.parcellockers.ParcelLockersPlugin"
    apiVersion = "1.13"
    prefix = "ParcelLockersPlugin"
    author = "Jakubk15"
    name = "ParcelLockers"
    description = "Plugin that provides functionality of parcel lockers in Minecraft, allowing players to send and receive parcels safely."
    website = "https://github.com/Jakubk15/ParcelLockers"
    version = "${project.version}"
    softDepend = listOf(
        "AuthMe",
        "BanManager",
        "BungeeChatAPI",
        "CMI",
        "DiscordSRV",
        "Factions",
        "Feudal",
        "ItemsAdder",
        "Essentials",
        "LegacyFactions",
        "Lands",
        "LuckPerms",
        "Multiverse-Core",
        "MVdWPlaceholderAPI",
        "MythicMobs",
        "mcMMO",
        "NashornPlus",
        "Nicky",
        "PlaceholderAPI",
        "ProtocolLib",
        "SimpleClans",
        "Towny",
        "TownyChat",
        "Vault",
        "WorldEdit")
    libraries = listOf(
        "org.openjdk.nashorn:nashorn-core:15.3"
    )
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(8))
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar> {
    archiveFileName.set("ParcelLockers v${project.version} (MC 1.8.8-1.19.x).jar")

    exclude(
        "org/intellij/lang/annotations/**",
        "org/jetbrains/annotations/**",
        "org/checkerframework/**",
        "META-INF/**",
        "javax/**",
        "lombok/**"
    )

    mergeServiceFiles()
    minimize()


    val prefix = "xyz.jakubk15.parcellockers.lib"
    listOf(
        "panda",
        "org.panda_lang",
        "org.panda_lang",
        "net.dzikoysk",
        "com.github.kangarko",
    ).forEach { pack ->
        relocate(pack, "$prefix.$pack")
    }
}

tasks {
    runServer {
        minecraftVersion("1.19.3")
    }
}
